# This workflow will rollback the last release if the tests fail. It will only run on dispatch.

name: Rollback

on:
  workflow_dispatch:
  

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rollback
        run: |
          git tag -d $(git describe --tags --abbrev=0)
          git push origin :$(git describe --tags --abbrev=0)